# This is a basic workflow to help you get started with Actions

name: push event

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step para a ilustrar eventos
        run: echo Hello, world!
